name: ci

on:
  push:
    branches:
      - "main"

env:
  IMAGE: jeremyatdockerhub/cullen
  TAG: 0.0.1
  PLATFORMS: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"

jobs:
  build-push-single:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: dagger call build-push
        uses: dagger/dagger-for-github@v5
        with:
          args: build-push --platform ${{ matrix.platform }} --image ${{ env.IMAGE }} --tag ${{ env.TAG }}
  pull-push-multi:
    needs: build-push-single
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: dagger call multi-push
        uses: dagger/dagger-for-github@v5
        with:
          args: multi-push --image ${{ env.IMAGE }} --platforms ${{ env.PLATFORMS }} --tag ${{ env.TAG }}
